apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mtcq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mtcq
    app.kubernetes.io/part-of: tkrw-pr712-0075-0073-app
  name: devfile-sample-mtcq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mtcq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mtcq
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0073-tenant/tkrw-pr712-0075-0073-app/devfile-sample-mtcq@sha256:1e785fe306258f1980117927b1a78c0cabf708b4c1a11c321b5e2e55b5d57811
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
